# We force the language to python
language: python

# We are using compiled extensions, and so we want to test with at least an
# "old" version of gcc and a "new" one.

matrix:
  include:
    # GCC 5 - default version for ubuntu 16.04 LTS.  Python 3.5
    - os: linux
      dist: trusty
      sudo: false
      python: 3.5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - build-essential
            - git
            - curl
            - pkg-config
            - locales
            - libgl1-mesa-glx
            - xvfb
            - libboost-all-dev
            - libopenblas-dev
            - liblapack-dev
            - libfftw3-dev
            - libflac-dev
            - libhdf5-dev
            - gcc-5
            - g++-5
      env:
        - MATRIX_EVAL="export CC=$(which gcc-5) && export CXX=$(which g++-5)"
    # GCC 5 - default version for ubuntu 16.04 LTS.  Python 3.6
    - os: linux
      dist: trusty
      sudo: false
      python: 3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - build-essential
            - git
            - curl
            - pkg-config
            - locales
            - libgl1-mesa-glx
            - xvfb
            - libboost-all-dev
            - libopenblas-dev
            - liblapack-dev
            - libfftw3-dev
            - libflac-dev
            - libhdf5-dev
            - gcc-5
            - g++-5
      env:
        - MATRIX_EVAL="export CC=$(which gcc-5) && export CXX=$(which g++-5)"
    # GCC 7 - default version for ubuntu 18.04 LTS.  Python 3.5
    - os: linux
      dist: trusty
      sudo: false
      python: 3.5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - build-essential
            - git
            - curl
            - pkg-config
            - locales
            - libgl1-mesa-glx
            - xvfb
            - libboost-all-dev
            - libopenblas-dev
            - liblapack-dev
            - libfftw3-dev
            - libflac-dev
            - libhdf5-dev
            - gcc-7
            - g++-7
      env:
        - MATRIX_EVAL="export CC=$(which gcc-7) && export CXX=$(which g++-7)"
    # GCC 7 - default version for ubuntu 18.04 LTS.  Python 3.6
    - os: linux
      dist: trusty
      sudo: false
      python: 3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - build-essential
            - git
            - curl
            - pkg-config
            - locales
            - libgl1-mesa-glx
            - xvfb
            - libboost-all-dev
            - libopenblas-dev
            - liblapack-dev
            - libfftw3-dev
            - libflac-dev
            - libhdf5-dev
            - gcc-7
            - g++-7
      env:
        - MATRIX_EVAL="export CC=$(which gcc-7) && export CXX=$(which g++-7)"

# Install remaining dependencies.

before_install:
    - eval "${MATRIX_EVAL}"
    - ./travis/travis_before-install.sh

# Install sotodlib
install:
    - python3 setup.py install

# Run tests.  Disable plot output which can be time-consuming.
script:
    - export SOTODLIB_TEST_DISABLE_PLOTS=1
    - python3 setup.py test
